package server.database;

import at.favre.lib.crypto.bcrypt.BCrypt;
import common.model.Categoria;
import common.model.Rol;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.*;
import java.time.LocalDateTime;

/**
 * Inicializa el esquema de la base de datos H2 creando las tablas necesarias
 * e insertando datos semilla (usuarios redactores y noticias de demostración).
 * <p>
 * Todas las operaciones se ejecutan en una sola transacción: si algo falla,
 * se revierte por completo y no deja cambios parciales.
 */
public final class DatabaseInitializer {
    private static final Logger LOGGER = LoggerFactory.getLogger(DatabaseInitializer.class);
    private static final int BCRYPT_COST = 12;
    private final DatabaseManager database;

    /**
     * Construye el inicializador con el gestor de base de datos a utilizar.
     *
     * @param database gestor que provee conexiones a la base de datos H2
     */
    public DatabaseInitializer(DatabaseManager database) {
        this.database = database;
    }

    /**
     * Intenta revertir todos los cambios de la transacción actual. Si el
     * rollback también falla (por ejemplo, la conexión ya está muerta),
     * lo registra en el log pero no lanza una excepción, para no enmascarar
     * el error original que provocó el rollback.
     *
     * @param connection conexión activa cuyo rollback se va a ejecutar
     */
    private static void rollback(Connection connection) {
        try {
            connection.rollback(); // Revierte todos los cambios no commiteados de esta conexión
        } catch (SQLException rollbackError) {
            LOGGER.error("No fue posible revertir la inicialización de H2", rollbackError); // Log del error si el rollback falla
        }
    }

    /**
     * Ejecuta la inicialización completa de la base de datos en una transacción
     * única: crea las tablas DDL e inserta los datos semilla. Si cualquier paso
     * falla, revierte todos los cambios y relanza la excepción.
     *
     * @throws SQLException si ocurre un error durante la creación de tablas
     *                      o la inserción de datos semilla
     */
    public void inicializar() throws SQLException {
        // Abre conexión y la cierra automáticamente al terminar (try-with-resources)
        try (Connection c = database.getConnection()) {
            c.setAutoCommit(false); // Desactiva auto-commit para controlar la transacción manualmente
            try {
                crearTablas(c); // Crea las tablas e índices si no existen
                datosIniciales(c);        // Inserta datos iniciales (autores y noticias de demostración)
                c.commit();     // Confirma todos los cambios de forma permanente
                LOGGER.info("Esquema H2 inicializado");
            } catch (SQLException | RuntimeException e) {
                rollback(c); // Revierte todos los cambios si algo falló
                throw e;     // Relanza la excepción para que el llamador la maneje
            }
        }
    }

    /**
     * Ejecuta las sentencias DDL para crear las tablas {@code autores},
     * {@code noticias} y {@code schema_metadata}, junto con los índices
     * de búsqueda. Todas las sentencias usan {@code IF NOT EXISTS},
     * por lo que son seguras de ejecutar múltiples veces.
     *
     * @param c conexión activa a la base de datos (no se cierra aquí)
     * @throws SQLException si alguna sentencia DDL falla
     */
    private void crearTablas(Connection c) throws SQLException {
        // Array con todas las sentencias DDL en orden de ejecución
        String[] ddl = {
                // Tabla de autores/redactores: usuario único, password hasheado, rol y estado
                """
                CREATE TABLE IF NOT EXISTS autores 
                (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
                usuario VARCHAR(50) NOT NULL UNIQUE, 
                password_hash VARCHAR(100) NOT NULL, 
                nombre VARCHAR(100) NOT NULL, 
                rol VARCHAR(20) NOT NULL, 
                activo BOOLEAN NOT NULL DEFAULT TRUE
                )
                """,
                // Tabla de noticias: contenido CLOB, FK a autores, versionado optimista y timestamps
                """
                CREATE TABLE IF NOT EXISTS noticias 
                (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
                titulo VARCHAR(200) NOT NULL, 
                contenido CLOB NOT NULL, 
                categoria VARCHAR(50) NOT NULL, 
                autor_id BIGINT NOT NULL, 
                version INTEGER NOT NULL DEFAULT 1 CHECK (version >= 1), 
                fecha_creacion TIMESTAMP NOT NULL, 
                fecha_modificacion TIMESTAMP NOT NULL, 
                CONSTRAINT fk_noticia_autor FOREIGN KEY (autor_id) REFERENCES autores(id)
                )
                """,
                // Tabla de metadatos del esquema: clave-valor para control de versiones de seed
                "CREATE TABLE IF NOT EXISTS schema_metadata (clave VARCHAR(100) PRIMARY KEY, valor VARCHAR(200) NOT NULL)",
                // Índice para acelerar consultas por categoría
                "CREATE INDEX IF NOT EXISTS idx_noticias_categoria ON noticias(categoria)",
                // Índice para acelerar consultas por autor
                "CREATE INDEX IF NOT EXISTS idx_noticias_autor ON noticias(autor_id)",
                // Índice descendente para listar noticias más recientes primero
                "CREATE INDEX IF NOT EXISTS idx_noticias_modificacion ON noticias(fecha_modificacion DESC)"
        };

        // Ejecuta cada sentencia DDL secuencialmente
        try (Statement s = c.createStatement()) {
            for (String sql : ddl) s.execute(sql); // Ejecuta sin esperar resultados
        }
    }

    /**
     * Inserta los datos iniciales de demostración: dos redactores y tres
     * noticias de ejemplo. Utiliza un flag en {@code schema_metadata}
     * ({@code seed.demo.v1}) para garantizar que el seed solo se aplique
     * una vez, incluso si el método se ejecuta múltiples veces.
     *
     * @param c conexión activa a la base de datos (no se cierra aquí)
     * @throws SQLException si ocurre un error en las inserciones
     */
    private void datosIniciales(Connection c) throws SQLException {
        // Inserta los dos redactores si no existen ya (idempotente)
        insertarAutorSiNoEsta(c, "redactor1", "redactor123", "Ana Torres");
        insertarAutorSiNoEsta(c, "redactor2", "noticias123", "Luis Mendoza");

        // Verifica si el seed de demostración ya se ejecutó antes
        try (PreparedStatement ps = c.prepareStatement("SELECT 1 FROM schema_metadata WHERE clave='seed.demo.v1'");
             ResultSet rs = ps.executeQuery()) {
            if (rs.next()) return; // Ya existe el flag: el seed ya se aplicó, salir sin hacer nada
        }

        // Obtiene los IDs de los autores para usarlos como FK en las noticias
        long autor1 = obtenerIdAutor(c, "redactor1");
        long autor2 = obtenerIdAutor(c, "redactor2");

        // Inserta tres noticias de demostración con categorías variadas
        insertarNoticia(c, "Java RMI conecta aplicaciones distribuidas", "RMI permite invocar métodos de objetos ubicados en otra máquina.", Categoria.TECNOLOGIA, autor1);
        insertarNoticia(c, "Nueva jornada de divulgación científica", "La comunidad universitaria compartirá proyectos y experimentos.", Categoria.CIENCIA, autor2);
        insertarNoticia(c, "Actividades culturales en el campus", "Se anunciaron talleres, conciertos y exposiciones para estudiantes.", Categoria.CULTURA, autor1);

        // Marca que el seed v1 ya se aplicó para no repetirlo en futuras ejecuciones
        try (PreparedStatement ps = c.prepareStatement("INSERT INTO schema_metadata(clave, valor) VALUES('seed.demo.v1','aplicada')")) {
            ps.executeUpdate();
        }
    }

    /**
     * Verifica si un autor ya existe por su nombre de usuario. Si no existe,
     * hashea su contraseña con BCrypt (costo 12) y lo inserta con rol
     * {@code REDACTOR} y estado activo. Es idempotente: no duplica ni falla
     * si el usuario ya está registrado.
     *
     * @param c        conexión activa a la base de datos (no se cierra aquí)
     * @param user     nombre de usuario único del redactor
     * @param password contraseña en texto plano que será hasheada con BCrypt
     * @param name     nombre completo del redactor
     * @throws SQLException si ocurre un error en la verificación o inserción
     */
    private void insertarAutorSiNoEsta(Connection c, String user, String password, String name) throws SQLException {
        // Consulta si el usuario ya existe
        try (PreparedStatement check = c.prepareStatement("SELECT 1 FROM autores WHERE usuario=?")) {
            check.setString(1, user); // Parámetro: nombre de usuario a buscar
            try (ResultSet rs = check.executeQuery()) {
                if (rs.next()) return; // Si encontró resultados, el autor ya existe: salir sin insertar
            }
        }

        // Comentar el hasheo si no se quiere encriptar
        // Hashea el password con BCrypt usando el costo configurado (12)
        String hash = BCrypt.withDefaults().hashToString(BCRYPT_COST, password.toCharArray());

        // Inserta el nuevo autor con rol REDACTOR y activo=TRUE
        try (PreparedStatement ps = c.prepareStatement("INSERT INTO autores(usuario,password_hash,nombre,rol,activo) VALUES(?,?,?,?,TRUE)")) {
            ps.setString(1, user);     // usuario
            ps.setString(2, hash);     // password hasheado || Texto plano si no se hasheo, cambiar variable
            ps.setString(3, name);     // nombre completo
            ps.setString(4, Rol.REDACTOR.name()); // rol como texto del enum
            ps.executeUpdate();
        }
    }

    /**
     * Obtiene el identificador único (ID) de un autor a partir de su
     * nombre de usuario.
     *
     * @param c    conexión activa a la base de datos (no se cierra aquí)
     * @param user nombre de usuario del autor a buscar
     * @return el ID (BIGINT) del autor encontrado
     * @throws SQLException si el autor no existe en la base de datos
     */
    private long obtenerIdAutor(Connection c, String user) throws SQLException {
        try (PreparedStatement ps = c.prepareStatement("SELECT id FROM autores WHERE usuario=?")) {
            ps.setString(1, user); // Parámetro: nombre de usuario a buscar
            try (ResultSet rs = ps.executeQuery()) {
                if (!rs.next()) throw new SQLException("Autor no encontrado"); // No se encontró: error
                return rs.getLong(1); // Retorna el ID de la columna 1
            }
        }
    }

    /**
     * Inserta una noticia con versión inicial 1 y timestamps actuales
     * para creación y modificación.
     *
     * @param c        conexión activa a la base de datos (no se cierra aquí)
     * @param title    título de la noticia
     * @param content  contenido completo del artículo
     * @param category categoría de la noticia (enum convertido a String)
     * @param author   ID del autor que escribe la noticia (FK a autores)
     * @throws SQLException si ocurre un error durante la inserción
     */
    private void insertarNoticia(Connection c, String title, String content, Categoria category, long author) throws SQLException {
        try (PreparedStatement ps = c.prepareStatement(
                "INSERT INTO noticias(titulo,contenido,categoria,autor_id,version,fecha_creacion,fecha_modificacion) VALUES(?,?,?,?,1,?,?)")) {
            LocalDateTime now = LocalDateTime.now();   // Timestamp actual para creación y modificación
            ps.setString(1, title);                 // título
            ps.setString(2, content);               // contenido
            ps.setString(3, category.name());       // categoría como texto del enum
            ps.setLong(4, author);                  // ID del autor (FK)
            // version se inserta como 1 directamente en el SQL
            ps.setObject(5, now);                   // fecha_creacion
            ps.setObject(6, now);                   // fecha_modificacion (igual a creación al ser nueva)
            ps.executeUpdate();
        }
    }
}
