package server.database;

import at.favre.lib.crypto.bcrypt.BCrypt;
import common.model.Categoria;
import common.model.Rol;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;

public final class DatabaseInitializer {
    private static final Logger LOGGER = LoggerFactory.getLogger(DatabaseInitializer.class);
    private static final int BCRYPT_COST = 12;
    private final DatabaseManager database;

    public DatabaseInitializer(DatabaseManager database) { this.database = database; }

    public void initialize() throws SQLException {
        try (Connection c = database.getConnection()) {
            c.setAutoCommit(false);
            try {
                createSchema(c); seed(c); c.commit(); LOGGER.info("Esquema H2 inicializado");
            } catch (SQLException | RuntimeException e) {
                rollback(c); throw e;
            }
        }
    }

    private void createSchema(Connection c) throws SQLException {
        String[] ddl = {
            "CREATE TABLE IF NOT EXISTS autores (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, usuario VARCHAR(50) NOT NULL UNIQUE, password_hash VARCHAR(100) NOT NULL, nombre VARCHAR(100) NOT NULL, rol VARCHAR(20) NOT NULL, activo BOOLEAN NOT NULL DEFAULT TRUE)",
            "CREATE TABLE IF NOT EXISTS noticias (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, titulo VARCHAR(200) NOT NULL, contenido CLOB NOT NULL, categoria VARCHAR(50) NOT NULL, autor_id BIGINT NOT NULL, version INTEGER NOT NULL DEFAULT 1 CHECK (version >= 1), fecha_creacion TIMESTAMP NOT NULL, fecha_modificacion TIMESTAMP NOT NULL, CONSTRAINT fk_noticia_autor FOREIGN KEY (autor_id) REFERENCES autores(id))",
            "CREATE TABLE IF NOT EXISTS schema_metadata (clave VARCHAR(100) PRIMARY KEY, valor VARCHAR(200) NOT NULL)",
            "CREATE INDEX IF NOT EXISTS idx_noticias_categoria ON noticias(categoria)",
            "CREATE INDEX IF NOT EXISTS idx_noticias_autor ON noticias(autor_id)",
            "CREATE INDEX IF NOT EXISTS idx_noticias_modificacion ON noticias(fecha_modificacion DESC)"
        };
        try (Statement s = c.createStatement()) { for (String sql : ddl) s.execute(sql); }
    }

    private void seed(Connection c) throws SQLException {
        insertAuthorIfMissing(c, "redactor1", "redactor123", "Ana Torres");
        insertAuthorIfMissing(c, "redactor2", "noticias123", "Luis Mendoza");
        try (PreparedStatement ps = c.prepareStatement("SELECT 1 FROM schema_metadata WHERE clave='seed.demo.v1'"); ResultSet rs = ps.executeQuery()) {
            if (rs.next()) return;
        }
        long autor1 = authorId(c, "redactor1"), autor2 = authorId(c, "redactor2");
        insertNews(c, "Java RMI conecta aplicaciones distribuidas", "RMI permite invocar métodos de objetos ubicados en otra máquina.", Categoria.TECNOLOGIA, autor1);
        insertNews(c, "Nueva jornada de divulgación científica", "La comunidad universitaria compartirá proyectos y experimentos.", Categoria.CIENCIA, autor2);
        insertNews(c, "Actividades culturales en el campus", "Se anunciaron talleres, conciertos y exposiciones para estudiantes.", Categoria.CULTURA, autor1);
        try (PreparedStatement ps = c.prepareStatement("INSERT INTO schema_metadata(clave, valor) VALUES('seed.demo.v1','aplicada')")) { ps.executeUpdate(); }
    }

    private void insertAuthorIfMissing(Connection c, String user, String password, String name) throws SQLException {
        try (PreparedStatement check = c.prepareStatement("SELECT 1 FROM autores WHERE usuario=?")) {
            check.setString(1, user); try (ResultSet rs = check.executeQuery()) { if (rs.next()) return; }
        }
        String hash = BCrypt.withDefaults().hashToString(BCRYPT_COST, password.toCharArray());
        try (PreparedStatement ps = c.prepareStatement("INSERT INTO autores(usuario,password_hash,nombre,rol,activo) VALUES(?,?,?,?,TRUE)")) {
            ps.setString(1,user); ps.setString(2,hash); ps.setString(3,name); ps.setString(4, Rol.REDACTOR.name()); ps.executeUpdate();
        }
    }
    private long authorId(Connection c, String user) throws SQLException {
        try (PreparedStatement ps = c.prepareStatement("SELECT id FROM autores WHERE usuario=?")) { ps.setString(1,user); try(ResultSet rs=ps.executeQuery()){if(!rs.next())throw new SQLException("Autor semilla ausente");return rs.getLong(1);} }
    }
    private void insertNews(Connection c,String title,String content,Categoria category,long author) throws SQLException {
        try (PreparedStatement ps=c.prepareStatement("INSERT INTO noticias(titulo,contenido,categoria,autor_id,version,fecha_creacion,fecha_modificacion) VALUES(?,?,?,?,1,?,?)")) {
            LocalDateTime now=LocalDateTime.now(); ps.setString(1,title);ps.setString(2,content);ps.setString(3,category.name());ps.setLong(4,author);ps.setObject(5,now);ps.setObject(6,now);ps.executeUpdate();
        }
    }
    private static void rollback(Connection connection) {
        try {
            connection.rollback();
        } catch (SQLException rollbackError) {
            LOGGER.error("No fue posible revertir la inicialización de H2", rollbackError);
        }
    }
}
